name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v6.0.0
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'v'
        tag_template: 'yyyy.i'
    
    - name: Build the Docker image
      id: build_image
      run: |
        docker build . --file dockerfile --tag typer:$RELEASE_TAG
        docker save typer:$RELEASE_TAG -o typer_$RELEASE_TAG
        tar -czvf typer_$RELEASE_TAG.tar.gz typer_$RELEASE_TAG
        ls
      env:
        RELEASE_TAG: ${{ steps.generate_release_tag.outputs.next_release_tag }}
      
    - name: Create new release
      id: create_release
      uses: comnoco/create-release-action@v2.0.5
      with:
        draft: false
        prerelease: false
        release_name: Typer ${{ steps.generate_release_tag.outputs.next_release_tag }}
        tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log files in workdir
      run: ls

    - name: Upload Docker image to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./typer*.tar.gz
        asset_name: typer_${{ steps.generate_release_tag.outputs.next_release_tag }}
        asset_content_type: application/gzip
